config/routes.rb
Rails.application.routes.draw do

  resources :products
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    p @product
  end

  def create
    @product = Product.new(product_params)
    @product.save
    redirect_to @product
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update(product_params)
    redirect_to @product
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to @product
  end

  private
  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with(model: @product, local: true) do |form| %>
    
    <%= form.label :Name %>
    <%= form.text_field :name %>

    <%= form.label :Price %>
    <%= form.text_field :price %>

    <%= form.submit %>
    
<%end%>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<h1> List of Products </h1>
<%= link_to 'Add Product', new_product_path %>

<table>
    <tr>
        <th>Product Name </th>
        <th>Product Price </th>
    </tr>

    <% @products.each do |p| %>
    <tr>
        <td><%= p.name %></td>
        <td><%= p.price %></td>
        <td><%= link_to 'Show', product_path(p)%></td>
        <td><%= link_to 'edit', edit_product_path(p)%></td>
        <td><%= link_to 'destroy', product_path(p),
                                    method: :"delete",
                                    data: {confirm: "Are you Sure"} %></td>
    </tr>
    <%end%>


</table>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
    <strong> Name </strong>
    <%= @product.name %><br>

    <strong> Address </strong>
    <%= @product.price %><br>

<%= link_to 'Back', products_path %>